function main_gui()
clear all
close all
% clc

img1 = 0;
img2 = 0;
% img1_rect = 0;

% создаем главное окно
main_fig = figure(...
...%     'Visible', 'off',...
    'Name', 'Вычисление дистанции',...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Color', [0.9412 0.9412 0.9412]...
    );

% создание осей для первого изображения
img1_axes = axes(...
    'Parent', main_fig,...
    'OuterPosition', [0 0.5 0.5 0.49],...
    'XTick', [],...
    'YTick', []...
    );
title(img1_axes, 'Левое изображение');

% создание осей для второго изображения
img2_axes = axes(...
    'Parent', main_fig,...
    'OuterPosition', [0.5 0.5 0.5 0.49],...
    'XTick', [],...
    'YTick', []...
    );
title(img2_axes, 'Правое изображение');

% создание осей для графика корреляционной функции
corr_fnc_axes = axes(...
    'Parent', main_fig,...
    'OuterPosition', [0.5 0.02 0.5 0.48], ...
    'XTick', [],...
    'YTick', []...
    );
title(corr_fnc_axes, 'Карта глубины');

% создание панели для элеметов управления
ctrl_panel = uipanel(...
    'Parent', main_fig,...
    'Position', [0.02 0.02 0.48 0.48],...
    'BorderWidth', 0 ...
    );

% создание кнопок открытия изображений
open_img1_button = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'pushbutton',...
    'String', 'Изображение №1',...
    'Units', 'normalize',...
    'Position', [0.05 0.9 0.425 0.1],...
    'Callback', @open_img1 ...
    );

open_img2_button = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'pushbutton',...
    'String', 'Изображение №2',...
    'Units', 'normalize',...
    'Position', [0.525 0.9 0.425 0.1],...
    'Callback', @open_img2 ...
    );

focus_text = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'text',...
    'String', 'Фокусное расстояние:',...
    'HorizontalAlignment', 'right',...
    'Units', 'normalize',...
    'Position', [0.05 0.775 0.425 0.1]...
    );

focus_edit = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'edit',...
    'String', '10',...
    'BackgroundColor', [1 1 1],...
    'Units', 'normalize',...
    'Position', [0.525 0.775 0.425 0.1]...
    );

lenses_distance_text = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'text',...
    'String', 'Расстояние между обьективами:',...
    'HorizontalAlignment', 'right',...
    'Units', 'normalize',...
    'Position', [0.05 0.65 0.425 0.1]...
    );

lenses_distance_edit = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'edit',...
    'String', '10',...
    'BackgroundColor', [1 1 1],...
    'Units', 'normalize',...
    'Position', [0.525 0.65 0.425 0.1]...
    );

pixel_size_text = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'text',...
    'String', 'Размер пикселя:',...
    'HorizontalAlignment', 'right',...
    'Units', 'normalize',...
    'Position', [0.05 0.525 0.425 0.1]...
    );

pixel_size_edit = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'edit',...
    'String', '10',...
    'BackgroundColor', [1 1 1],...
    'Units', 'normalize',...
    'Position', [0.525 0.525 0.425 0.1]...
    );

distance_text = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'text',...
    'String', 'Максимальное смещение:',...
    'HorizontalAlignment', 'right',...
    'Units', 'normalize',...
    'Position', [0.05 0.15 0.425 0.1]...
    );

distance_edit = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'edit',...
    'String', '16',...
    'BackgroundColor', [1 1 1],...
    'Units', 'normalize',...
    'Position', [0.525 0.15 0.425 0.1]...
    );

win_size_text = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'text',...
    'String', 'Размер области:',...
    'HorizontalAlignment', 'right',...
    'Units', 'normalize',...
    'Position', [0.05 0.025 0.425 0.1]...
    );

win_size_edit = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'edit',...
    'String', '9',...
    'BackgroundColor', [1 1 1],...
    'Units', 'normalize',...
    'Position', [0.525 0.025 0.425 0.1]...
    );

corr_type_text = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'text',...
    'String', 'Корр. ф-ция:',...
    'HorizontalAlignment', 'right',...
    'Units', 'normalize',...
    'Position', [0.05 0.4 0.425 0.1]...
    );

corr_type_edit = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'popupmenu',...
    'String', 'SAD|SSD|NCC',...
    'BackgroundColor', [1 1 1],...
    'Units', 'normalize',...
    'Position', [0.525 0.4 0.425 0.1]...
    );

calculate_button = uicontrol(...
    'Parent', ctrl_panel,...
    'Style', 'pushbutton',...
    'String', 'Получить карту глубины',...
    'Units', 'normalize',...
    'Position', [0.2 0.275 0.6 0.1],...
    'Callback', @calculate ...
    );

% inspect(corr_type_edit)

    function open_img1(obj_handle, event)
        [filename, user_canceled] = imgetfile();
        if user_canceled
            return
        end
        img1 = imread(filename);
        imshow(img1, 'Parent', img1_axes);
        title(img1_axes, 'Первое изображение');
        img1_info = imfinfo(filename);
        if (getfield(img1_info,'ColorType') == 'truecolor')
            img1 = rgb2gray(img1);
        else
            if(getfield(img1_info,'ColorType') == 'grayscale')        
            else
                error('The Color Type of left Image is not acceptable.');
            end
        end
%         img1_rect = imrect(img1_axes);
    end

    function open_img2(obj_handle, event)
        [filename, user_canceled] = imgetfile();
        if user_canceled
            return
        end
        img2 = imread(filename);
        imshow(img2, 'Parent', img2_axes);
        title(img2_axes, 'Второе изображение');
        img2_info = imfinfo(filename);
        if (getfield(img2_info,'ColorType') == 'truecolor')
            img2 = rgb2gray(img2);
        else
            if(getfield(img2_info,'ColorType') == 'grayscale')        
            else
                error('The Color Type of left Image is not acceptable.');
            end
        end
    end

    function calculate(obj_handle, event)

%         dx = abs(dx_img2 - x_win)
        F = str2num(get(focus_edit, 'String'));
        L = str2num(get(lenses_distance_edit, 'String'));
        w = str2num(get(pixel_size_edit, 'String'));
        corr_type_value = get(corr_type_edit, 'Value');
        d_max = str2num(get(distance_edit, 'String'));
        win_size = str2num(get(win_size_edit, 'String'));
        if corr_type_value == 1
            corr_type = 'SAD';
        elseif corr_type_value == 2
            corr_type = 'SSD';
        elseif corr_type_value == 3
            corr_type = 'NCC';
        else
            corr_type = 'NCC';
        end
        disp_map = dense_match(img1, img2, win_size, 0, d_max, corr_type);
        distance_map = F.*L./(w.*disp_map);
        
%         set(distance_edit, 'String', num2str(distance));
%         set(win_size_edit, 'String',...
%             strcat('[', num2str(width_win), ', ', num2str(hight_win), ']'));
        imagesc(distance_map, 'Parent', corr_fnc_axes);
        colormap(gray);
        colorbar;
        title(corr_fnc_axes, 'Карта глубины');
    end
end